name: Build Next.js app with PNPM

on:
  push:
    branches:
      - main
      - develop
      - feat/*
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build with Next.js
        run: bun run build